### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by ljvmiranda921** [thinkingmachines/geomancer#14]
The main challenge here is to mock the bigquery client. Still not sure how this will all work, but we should have atleast good test coverage for this project.

**Comment by marksteve** [comment]
We can use https://www.gaia-gis.it/fossil/libspatialite/index to test SQL queries without querying BQ directly

**Comment by ljvmiranda921** [comment]
I can take a look at this this weekend! So main idea is to create test fixtures from a SQLite DB

**Comment by ljvmiranda921** [comment]
Some notes:
- Create a SQLite `source` test database by loading Philippine shapefiles from Geofrabrik. Check [this](https://www.gaia-gis.it/gaia-sins/spatialite-tutorial-2.3.1.html#t3.2) tutorial. Although I don't think we'll need the whole thing, especially if we're going to `commit` this? Maybe just get via `wget` instead
- The same goes for a `test` database of points
- https://www.gaia-gis.it/gaia-sins/BLOB-Geometry.html
- Use `AsText`
- Just load the `CSV` with `WKT` columns into the db

```python
import sqlite3
conn = sqlite3.connect('test_source.sqlite')
conn.enable_load_extension(True)

try:
    conn.load_extension('mod_spatialite.so')
except OperationalError:
    conn.load_extension('libspatialite.so')

cursor = conn.cursor()
cursor.execute(QUERY)
```

More info on [`mod_spatialite.so`](https://www.gaia-gis.it/fossil/libspatialite/wiki?name=mod_spatialite)
