### ISSUE TITLE
Add CI/CD Pipeline

### ISSUE THREAD

**Issue by ljvmiranda921** [thinkingmachines/geomancer#17]
Some options:
- [Azure Pipelines](https://azure.microsoft.com/en-us/services/devops/pipelines/)
- [CircleCI](https://circleci.com/)

## Requirements
1. Must be free for open-source projects
2. Easy deployment (just a `yaml` file, no need for on-prem solutions)
3. Should support Docker, build matrices, and cron jobs

**Comment by marksteve** [comment]
@ljvmiranda921 https://cirrus-ci.org/
