### ISSUE TITLE
Change the truncation of coordinates from 4 decimal places to 8 decimal places

### ISSUE THREAD

**Issue by ardieorden** [thinkingmachines/geomancer#68]
Let's preserve the positional accuracy of the input WKTs and output WKTs. 8 decimal places is a reasonable threshold since 9 decimal places is already 0.01 mm.

**Comment by ljvmiranda921** [comment]
When does the truncation happen? 
When loading into dataframe before `cast()` or when getting the results back to GBQ? Or both?

**Comment by ardieorden** [comment]
I think it truncates at ` pd.read_gbq`. The issue isn't due to Geomancer, I'll close this now.
