### ISSUE TITLE
Can’t extract features greater than 11,000 fclass count

### ISSUE THREAD

**Issue by tgvgamboa** [thinkingmachines/geomancer#76]
### Issue Description
Unable to extract features for a data frame of 56,761 rows if the feature class has a count of around 11,000 in its dataset.

(Though it works if the feature class has a count of around 5,000 in its dataset, count of around 7,000 works sometimes)

### Steps to reproduce the issue
```python
df = pd.read_csv('sample.csv')

instance_primary = DistanceToNearest(
    'primary',
    source_table = 'project.dataset_id.gis_osm_roads_free_1',
    feature_name = 'dist_primary'
)

test_primary = instance_primary.cast(df, dburl = 'bigquery://project')
```

### What's the expected result?
- no error

### What's the actual result?
- DatabaseError [Link to Colab Notebook](https://colab.research.google.com/drive/1DHav6WD0M8OVwBbq0FYPF7w_Q6-c4xEC?authuser=1#scrollTo=BJqyzrWZIMkl)

### Additional details / screenshot
![image](https://user-images.githubusercontent.com/50901624/58402823-c67adf80-8093-11e9-8032-c5da07b7f13d.png)

**Comment by ljvmiranda921** [comment]
Let me try to reproduce the error first. So this is what the resulting query looks like:

```sql
WITH `pois` AS 
(SELECT `project.sg_osm.gis_osm_roads_free_1`.`osm_id` AS `osm_id`, `project.sg_osm.gis_osm_roads_free_1`.`WKT` AS `WKT` 
FROM `project.sg_osm.gis_osm_roads_free_1` 
WHERE `project.sg_osm.gis_osm_roads_free_1`.`fclass` = @`fclass_1`), 
`pairs` AS 
(SELECT `project.geomancer.673a6a5c238645c0a84270f8992ee5de`.`Longitude` AS `Longitude`, `project.geomancer.673a6a5c238645c0a84270f8992ee5de`.`Latitude` AS `Latitude`, `project.geomancer.673a6a5c238645c0a84270f8992ee5de`.`WKT` AS `WKT`, `project.geomancer.673a6a5c238645c0a84270f8992ee5de`.`__index_level_0__` AS `__index_level_0__`, ST_Distance(ST_GeogFromText(`project.geomancer.673a6a5c238645c0a84270f8992ee5de`.`WKT`), ST_GeogFromText(`pois`.`WKT`)) AS `dist_primary` 
FROM `project.geomancer.673a6a5c238645c0a84270f8992ee5de`, `pois` 
WHERE ST_Distance(ST_GeogFromText(`project.geomancer.673a6a5c238645c0a84270f8992ee5de`.`WKT`), ST_GeogFromText(`pois`.`WKT`)) < @`ST_Distance_1`)
 SELECT `Longitude` AS `Longitude`, `Latitude` AS `Latitude`, `WKT` AS `WKT`, `dist_primary` AS `dist_primary` 
FROM (SELECT `Longitude`, `Latitude`, `WKT`, `__index_level_0__`, `dist_primary` 
FROM (SELECT `pairs`.`Longitude` AS `Longitude`, `pairs`.`Latitude` AS `Latitude`, `pairs`.`WKT` AS `WKT`, `pairs`.`__index_level_0__` AS `__index_level_0__`, `pairs`.`dist_primary` AS `dist_primary`, row_number() OVER (PARTITION BY `pairs`.`__index_level_0__` ORDER BY `pairs`.`dist_primary` ASC) AS `row_number` 
FROM `pairs`) 
WHERE `row_number` = @`row_number_1`)
```

Looking at the BQ job history, we get an error like this:

> Query exceeded resource limits. 16390.825350959585 CPU seconds were used, and this query must > use less than 5300.0 CPU seconds.

I can reproduce the error by running the command above with the following parameters: `fclass_1`=`primary`, `row_number`=1, `ST_Distance_1`=10000

**Comment by ardieorden** [comment]
@ljvmiranda921 I've encountered this error before. The way to solve it is to limit the distance to a smaller radius, say 5000

**Comment by ardieorden** [comment]
@ljvmiranda921 Another way is to limit the rows of the POI dataset. You can perform a UNION ALL to combine the results later on.

**Comment by ardieorden** [comment]
@ljvmiranda921 The query is inherently intensive because it involves a cross join. Apparently, BQ also has limits in terms of the query time.

**Comment by ljvmiranda921** [comment]
Gotcha. I think this is already solved by using a smaller `within` value. Can you try it out, @tiffanigracegamboa ? If it works then please close the issue.

Thanks @ardieorden for getting on this! :+1:

**Comment by tgvgamboa** [comment]
Cool, works perfectly! Thanks @ardieorden and @ljvmiranda921 !
